// Code generated by mockery v2.12.3. DO NOT EDIT.

package yamlp

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockReaderFunctor is an autogenerated mock type for the ReaderFunctor type
type MockReaderFunctor struct {
	mock.Mock
}

// Apply provides a mock function with given fields: perform
func (_m *MockReaderFunctor) Apply(perform func(io.Reader) error) error {
	ret := _m.Called(perform)

	var r0 error
	if rf, ok := ret.Get(0).(func(func(io.Reader) error) error); ok {
		r0 = rf(perform)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type NewMockReaderFunctorT interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockReaderFunctor creates a new instance of MockReaderFunctor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockReaderFunctor(t NewMockReaderFunctorT) *MockReaderFunctor {
	mock := &MockReaderFunctor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
