// Code generated by mockery. DO NOT EDIT.

package dsco

import (
	svalue "github.com/byte4ever/dsco/svalue"
	mock "github.com/stretchr/testify/mock"
)

// MockNamedStringValuesProvider is an autogenerated mock type for the NamedStringValuesProvider type
type MockNamedStringValuesProvider struct {
	mock.Mock
}

type MockNamedStringValuesProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNamedStringValuesProvider) EXPECT() *MockNamedStringValuesProvider_Expecter {
	return &MockNamedStringValuesProvider_Expecter{mock: &_m.Mock}
}

// GetName provides a mock function with given fields:
func (_m *MockNamedStringValuesProvider) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockNamedStringValuesProvider_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockNamedStringValuesProvider_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockNamedStringValuesProvider_Expecter) GetName() *MockNamedStringValuesProvider_GetName_Call {
	return &MockNamedStringValuesProvider_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockNamedStringValuesProvider_GetName_Call) Run(run func()) *MockNamedStringValuesProvider_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNamedStringValuesProvider_GetName_Call) Return(_a0 string) *MockNamedStringValuesProvider_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNamedStringValuesProvider_GetName_Call) RunAndReturn(run func() string) *MockNamedStringValuesProvider_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// GetStringValues provides a mock function with given fields:
func (_m *MockNamedStringValuesProvider) GetStringValues() svalue.Values {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStringValues")
	}

	var r0 svalue.Values
	if rf, ok := ret.Get(0).(func() svalue.Values); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(svalue.Values)
		}
	}

	return r0
}

// MockNamedStringValuesProvider_GetStringValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStringValues'
type MockNamedStringValuesProvider_GetStringValues_Call struct {
	*mock.Call
}

// GetStringValues is a helper method to define mock.On call
func (_e *MockNamedStringValuesProvider_Expecter) GetStringValues() *MockNamedStringValuesProvider_GetStringValues_Call {
	return &MockNamedStringValuesProvider_GetStringValues_Call{Call: _e.mock.On("GetStringValues")}
}

func (_c *MockNamedStringValuesProvider_GetStringValues_Call) Run(run func()) *MockNamedStringValuesProvider_GetStringValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNamedStringValuesProvider_GetStringValues_Call) Return(_a0 svalue.Values) *MockNamedStringValuesProvider_GetStringValues_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNamedStringValuesProvider_GetStringValues_Call) RunAndReturn(run func() svalue.Values) *MockNamedStringValuesProvider_GetStringValues_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNamedStringValuesProvider creates a new instance of MockNamedStringValuesProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNamedStringValuesProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNamedStringValuesProvider {
	mock := &MockNamedStringValuesProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
