// Code generated by mockery. DO NOT EDIT.

package dsco

import mock "github.com/stretchr/testify/mock"

// MockInventoryReporter is an autogenerated mock type for the InventoryReporter type
type MockInventoryReporter struct {
	mock.Mock
}

type MockInventoryReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryReporter) EXPECT() *MockInventoryReporter_Expecter {
	return &MockInventoryReporter_Expecter{mock: &_m.Mock}
}

// ReportInventory provides a mock function with given fields: model
func (_m *MockInventoryReporter) ReportInventory(model ModelInterface) (LayerInventory, error) {
	ret := _m.Called(model)

	if len(ret) == 0 {
		panic("no return value specified for ReportInventory")
	}

	var r0 LayerInventory
	var r1 error
	if rf, ok := ret.Get(0).(func(ModelInterface) (LayerInventory, error)); ok {
		return rf(model)
	}
	if rf, ok := ret.Get(0).(func(ModelInterface) LayerInventory); ok {
		r0 = rf(model)
	} else {
		r0 = ret.Get(0).(LayerInventory)
	}

	if rf, ok := ret.Get(1).(func(ModelInterface) error); ok {
		r1 = rf(model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryReporter_ReportInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportInventory'
type MockInventoryReporter_ReportInventory_Call struct {
	*mock.Call
}

// ReportInventory is a helper method to define mock.On call
//   - model ModelInterface
func (_e *MockInventoryReporter_Expecter) ReportInventory(model interface{}) *MockInventoryReporter_ReportInventory_Call {
	return &MockInventoryReporter_ReportInventory_Call{Call: _e.mock.On("ReportInventory", model)}
}

func (_c *MockInventoryReporter_ReportInventory_Call) Run(run func(model ModelInterface)) *MockInventoryReporter_ReportInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ModelInterface))
	})
	return _c
}

func (_c *MockInventoryReporter_ReportInventory_Call) Return(_a0 LayerInventory, _a1 error) *MockInventoryReporter_ReportInventory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryReporter_ReportInventory_Call) RunAndReturn(run func(ModelInterface) (LayerInventory, error)) *MockInventoryReporter_ReportInventory_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInventoryReporter creates a new instance of MockInventoryReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryReporter {
	mock := &MockInventoryReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
