// Code generated by mockery v2.12.3. DO NOT EDIT.

package dsco

import mock "github.com/stretchr/testify/mock"

// mockReportInterface is an autogenerated mock type for the reportInterface type
type mockReportInterface struct {
	mock.Mock
}

// addEntry provides a mock function with given fields: e
func (_m *mockReportInterface) addEntry(e ReportEntry) {
	_m.Called(e)
}

// perEntryReport provides a mock function with given fields:
func (_m *mockReportInterface) perEntryReport() []error {
	ret := _m.Called()

	var r0 []error
	if rf, ok := ret.Get(0).(func() []error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}

	return r0
}

type newMockReportInterfaceT interface {
	mock.TestingT
	Cleanup(func())
}

// newMockReportInterface creates a new instance of mockReportInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockReportInterface(t newMockReportInterfaceT) *mockReportInterface {
	mock := &mockReportInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
