// Code generated by mockery. DO NOT EDIT.

package dsco

import mock "github.com/stretchr/testify/mock"

// MockKeyFormatter is an autogenerated mock type for the KeyFormatter type
type MockKeyFormatter struct {
	mock.Mock
}

type MockKeyFormatter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeyFormatter) EXPECT() *MockKeyFormatter_Expecter {
	return &MockKeyFormatter_Expecter{mock: &_m.Mock}
}

// FormatKey provides a mock function with given fields: aliasPath
func (_m *MockKeyFormatter) FormatKey(aliasPath string) string {
	ret := _m.Called(aliasPath)

	if len(ret) == 0 {
		panic("no return value specified for FormatKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(aliasPath)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockKeyFormatter_FormatKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FormatKey'
type MockKeyFormatter_FormatKey_Call struct {
	*mock.Call
}

// FormatKey is a helper method to define mock.On call
//   - aliasPath string
func (_e *MockKeyFormatter_Expecter) FormatKey(aliasPath interface{}) *MockKeyFormatter_FormatKey_Call {
	return &MockKeyFormatter_FormatKey_Call{Call: _e.mock.On("FormatKey", aliasPath)}
}

func (_c *MockKeyFormatter_FormatKey_Call) Run(run func(aliasPath string)) *MockKeyFormatter_FormatKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockKeyFormatter_FormatKey_Call) Return(_a0 string) *MockKeyFormatter_FormatKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyFormatter_FormatKey_Call) RunAndReturn(run func(string) string) *MockKeyFormatter_FormatKey_Call {
	_c.Call.Return(run)
	return _c
}

// LayerKind provides a mock function with no fields
func (_m *MockKeyFormatter) LayerKind() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LayerKind")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockKeyFormatter_LayerKind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LayerKind'
type MockKeyFormatter_LayerKind_Call struct {
	*mock.Call
}

// LayerKind is a helper method to define mock.On call
func (_e *MockKeyFormatter_Expecter) LayerKind() *MockKeyFormatter_LayerKind_Call {
	return &MockKeyFormatter_LayerKind_Call{Call: _e.mock.On("LayerKind")}
}

func (_c *MockKeyFormatter_LayerKind_Call) Run(run func()) *MockKeyFormatter_LayerKind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKeyFormatter_LayerKind_Call) Return(_a0 string) *MockKeyFormatter_LayerKind_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyFormatter_LayerKind_Call) RunAndReturn(run func() string) *MockKeyFormatter_LayerKind_Call {
	_c.Call.Return(run)
	return _c
}

// LayerName provides a mock function with no fields
func (_m *MockKeyFormatter) LayerName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LayerName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockKeyFormatter_LayerName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LayerName'
type MockKeyFormatter_LayerName_Call struct {
	*mock.Call
}

// LayerName is a helper method to define mock.On call
func (_e *MockKeyFormatter_Expecter) LayerName() *MockKeyFormatter_LayerName_Call {
	return &MockKeyFormatter_LayerName_Call{Call: _e.mock.On("LayerName")}
}

func (_c *MockKeyFormatter_LayerName_Call) Run(run func()) *MockKeyFormatter_LayerName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKeyFormatter_LayerName_Call) Return(_a0 string) *MockKeyFormatter_LayerName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKeyFormatter_LayerName_Call) RunAndReturn(run func() string) *MockKeyFormatter_LayerName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKeyFormatter creates a new instance of MockKeyFormatter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeyFormatter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeyFormatter {
	mock := &MockKeyFormatter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
