// Code generated by mockery. DO NOT EDIT.

package dsco

import mock "github.com/stretchr/testify/mock"

// MockPoliciesGetter is an autogenerated mock type for the PoliciesGetter type
type MockPoliciesGetter struct {
	mock.Mock
}

type MockPoliciesGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPoliciesGetter) EXPECT() *MockPoliciesGetter_Expecter {
	return &MockPoliciesGetter_Expecter{mock: &_m.Mock}
}

// GetPolicies provides a mock function with given fields:
func (_m *MockPoliciesGetter) GetPolicies() (constraintLayerPolicies, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPolicies")
	}

	var r0 constraintLayerPolicies
	var r1 error
	if rf, ok := ret.Get(0).(func() (constraintLayerPolicies, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() constraintLayerPolicies); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(constraintLayerPolicies)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPoliciesGetter_GetPolicies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPolicies'
type MockPoliciesGetter_GetPolicies_Call struct {
	*mock.Call
}

// GetPolicies is a helper method to define mock.On call
func (_e *MockPoliciesGetter_Expecter) GetPolicies() *MockPoliciesGetter_GetPolicies_Call {
	return &MockPoliciesGetter_GetPolicies_Call{Call: _e.mock.On("GetPolicies")}
}

func (_c *MockPoliciesGetter_GetPolicies_Call) Run(run func()) *MockPoliciesGetter_GetPolicies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPoliciesGetter_GetPolicies_Call) Return(_a0 constraintLayerPolicies, _a1 error) *MockPoliciesGetter_GetPolicies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPoliciesGetter_GetPolicies_Call) RunAndReturn(run func() (constraintLayerPolicies, error)) *MockPoliciesGetter_GetPolicies_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPoliciesGetter creates a new instance of MockPoliciesGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPoliciesGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPoliciesGetter {
	mock := &MockPoliciesGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
