// Code generated by mockery v2.13.1. DO NOT EDIT.

package dsco

import mock "github.com/stretchr/testify/mock"

// MockLayer is an autogenerated mock type for the Layer type
type MockLayer struct {
	mock.Mock
}

// register provides a mock function with given fields: to
func (_m *MockLayer) register(to *layerBuilder) error {
	ret := _m.Called(to)

	var r0 error
	if rf, ok := ret.Get(0).(func(*layerBuilder) error); ok {
		r0 = rf(to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockLayer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockLayer creates a new instance of MockLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockLayer(t mockConstructorTestingTNewMockLayer) *MockLayer {
	mock := &MockLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
