// Code generated by mockery v2.13.1. DO NOT EDIT.

package merror

import mock "github.com/stretchr/testify/mock"

// mockTestError is an autogenerated mock type for the testError type
type mockTestError struct {
	mock.Mock
}

// Error provides a mock function with given fields:
func (_m *mockTestError) Error() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTnewMockTestError interface {
	mock.TestingT
	Cleanup(func())
}

// newMockTestError creates a new instance of mockTestError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockTestError(t mockConstructorTestingTnewMockTestError) *mockTestError {
	mock := &mockTestError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
