// Code generated by mockery v2.13.1. DO NOT EDIT.

package walker

import mock "github.com/stretchr/testify/mock"

// MockPoliciesGetter is an autogenerated mock type for the PoliciesGetter type
type MockPoliciesGetter struct {
	mock.Mock
}

// GetPolicies provides a mock function with given fields: fillReporter
func (_m *MockPoliciesGetter) GetPolicies(fillReporter FillReporter) constraintLayerPolicies {
	ret := _m.Called(fillReporter)

	var r0 constraintLayerPolicies
	if rf, ok := ret.Get(0).(func(FillReporter) constraintLayerPolicies); ok {
		r0 = rf(fillReporter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(constraintLayerPolicies)
		}
	}

	return r0
}

type mockConstructorTestingTNewMockPoliciesGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockPoliciesGetter creates a new instance of MockPoliciesGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockPoliciesGetter(t mockConstructorTestingTNewMockPoliciesGetter) *MockPoliciesGetter {
	mock := &MockPoliciesGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
