// Code generated by mockery v2.13.1. DO NOT EDIT.

package ifaces

import (
	"github.com/byte4ever/dsco/internal/fvalue"
	"github.com/byte4ever/dsco/internal/plocation"

	"github.com/stretchr/testify/mock"

	"reflect"
)

// MockModelInterface is an autogenerated mock type for the ModelInterface type
type MockModelInterface struct {
	mock.Mock
}

// ApplyOn provides a mock function with given fields: g
func (_m *MockModelInterface) ApplyOn(g Getter) (fvalue.Values, error) {
	ret := _m.Called(g)

	var r0 fvalue.Values
	if rf, ok := ret.Get(0).(func(Getter) fvalue.Values); ok {
		r0 = rf(g)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fvalue.Values)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(Getter) error); ok {
		r1 = rf(g)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Fill provides a mock function with given fields: inputModelValue, layers
func (_m *MockModelInterface) Fill(inputModelValue reflect.Value, layers []fvalue.Values) (plocation.Locations, error) {
	ret := _m.Called(inputModelValue, layers)

	var r0 plocation.Locations
	if rf, ok := ret.Get(0).(func(reflect.Value, []fvalue.Values) plocation.Locations); ok {
		r0 = rf(inputModelValue, layers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plocation.Locations)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(reflect.Value, []fvalue.Values) error); ok {
		r1 = rf(inputModelValue, layers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFieldValuesFor provides a mock function with given fields: id, v
func (_m *MockModelInterface) GetFieldValuesFor(id string, v reflect.Value) fvalue.Values {
	ret := _m.Called(id, v)

	var r0 fvalue.Values
	if rf, ok := ret.Get(0).(func(string, reflect.Value) fvalue.Values); ok {
		r0 = rf(id, v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fvalue.Values)
		}
	}

	return r0
}

// TypeName provides a mock function with given fields:
func (_m *MockModelInterface) TypeName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewMockModelInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockModelInterface creates a new instance of MockModelInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockModelInterface(t mockConstructorTestingTNewMockModelInterface) *MockModelInterface {
	mock := &MockModelInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
