// Code generated by mockery v2.12.3. DO NOT EDIT.

package strukt

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockReadCloseProvider is an autogenerated mock type for the ReadCloseProvider type
type MockReadCloseProvider struct {
	mock.Mock
}

// ReadClose provides a mock function with given fields: perform
func (_m *MockReadCloseProvider) ReadClose(perform func(io.Reader) error) error {
	ret := _m.Called(perform)

	var r0 error
	if rf, ok := ret.Get(0).(func(func(io.Reader) error) error); ok {
		r0 = rf(perform)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type NewMockReadCloseProviderT interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockReadCloseProvider creates a new instance of MockReadCloseProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockReadCloseProvider(t NewMockReadCloseProviderT) *MockReadCloseProvider {
	mock := &MockReadCloseProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
